
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678901','Head First HTML5',2,2011,'Mc GrawHill','Español','Head First es un libro recomendado para aquellas personas que no conocen el lenguaje de programacion java. Ya que gracias a su forma de explicar es muy facil, sencillo y divertido entender este lenguaje');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678902','Head First Desing Patterns',1,2010,'Addison Wesley','Ingles','Desing Patterns es un libro dedicado a conocer los diversos patrones de desarrollo que existen actualmente. Servira tanto a profesionales con muy poca experiencia en programacion como a aquellos programadores experimentados.');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678903','Los pilares de la tierra',3,2009,'DeBolsillo','Español','Libro que narra la historia de Tom el constructor y su familia, describe todas las penumbres que tienen que pasar hasta lograr construir una catedral en la Inglaterra de la edad media');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678904','El simbolo perdido',2,2008,'Planeta Internacional','Español','La novela mas esperada despues del Codigo de da Vinci');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678905','El codigo Da Vinci',1,2007,'Planeta Internacional','Español','Novela que relata los secretos ocultos detras de la Mona Lisa y el circulo de hombres desconocidos que se hacen llamar los caballeros templarios los cuales tienen una estructura y fin en comun');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678906','UML Gota a Gota',3,2009,'Pearson','Español','Modelado y desarrollo de aplicaciones. Utilzando las herramientas de modelado que existen actualmente para desarrollo de la programacion orientada a objetos');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678907','Don quijote de la mancha',10,2009,'Castalia Prima','Español','Acompaña al incanzable Don Quijote de la mancha y su fiel escudero Sancho Panza por las aventuras que jamas imaginarias posibles dentro de un mundo de realidad y fantasia');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678908','Design Patterns',2,2005,'Addison Wesley','Ingles','Design Patterns es un grandioso libro para conocer los patrones de diseño que actualmente se utilizan para la solucion de problemas.');
INSERT INTO `libro` (`isbn`,`titulo`,`edicion`,`añoEdicion`,`editorial`,`idioma`,`descripcion`) VALUES ('12345678909','Steve Jobs',1,2011,'Walter Isaacson','Español','Conoce la interesante vida que tuvo Steve Jobs y como impacto al mundo entero con sus inveciones informaticas mas sofisticadas desarrolladas por MAC');
